### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by JesterlJoker** [Fj0rtizFredde/FGPS#1]
This is not an issue.

Can I add some updates for this?

Like new commands, commits, and edits. I would love to add some new updates to this and of course I will add it here on your github. Nothing will change except the updates.

waiting for a reply.

**Comment by Fj0rtizFredde** [comment]
Sure thing. I don't play the game or maintain any code so go ahead.

**Comment by JesterlJoker** [comment]
Oh okay, then one last thing, I'll also like to re-release the filterscript too, the updated one I mean and I'll still use your link.

Just so other's can use. Specially the newbies. Since most includes and filters are using complicated scripting method already.

**Comment by Fj0rtizFredde** [comment]
Go ahead and re-release it. Just keep me in the credits in your code and I will be happy. :)

**Comment by JesterlJoker** [comment]
Of course, the credits won't be removed except the ones that are being changed such as new cmd incude or etc that will be added. Updates will be coming soon. Since I found issues while using the filterscript. I'll also be using it since it's already a handy tool. Good job on creating it by the way. :+1:

**Comment by JesterlJoker** [comment]
Seems like I'll have to fork or have to move it to my repository since I can't edit on yours. It'll be temporary until you allow me to edit on your repository.

**Comment by Fj0rtizFredde** [comment]
I added you to the collaborator list. But feel free to make your own repository if you want. I haven't touched the code in years and I have no future plans to do so either.

**Comment by JesterlJoker** [comment]
Well I'll just make a repository about it then just to make it easier to navigate when updates are coming... I'll still keep the name and I'll leave a link below to my repository and link people to your repository so that they couldn't say I'm claiming the filter on my own

**Comment by Fj0rtizFredde** [comment]
Sounds good!

Looking forward to see your work.

Happy coding! :smiley:
